### ISSUE TITLE
add ability to send email when new blog post added

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#32]
we use hexo to generate blog posts and then restart the server after generating the new pages would be good if the blog post could be emailed to a mailing list on restart.
would use smtp like the contact form.

**Comment by benwiley4000** [comment]
How is the list of mail recipients determined?

**Comment by butlerx** [comment]
thats handled by a different system all you would need to do is send it to one email address

**Comment by benwiley4000** [comment]
Ok. I might need a little more definition about scope. There are several subtasks here:

1. After server restart, determine which post(s) are considered "new," and obtain relevant data (title, blurb, author, date posted).
2. Determine the list of email recipients, either by performing a query or receiving a list from somewhere.
3. Send SMTP email to specified email list, with relevant data.

I originally assumed all these tasks would be handled by the Node server but I'm now wondering if you're planning to provide the email list (#2) and/or email body (#1) via REST endpoint instead of direct query inside the Node server?

**Comment by butlerx** [comment]
yes too 1 and 3 but number 2 is already done my our mailing list server and is an address that will never change. so it could just be read from a config

**Comment by benwiley4000** [comment]
Aha got it. Thanks for the quick reply! Could you please specify where that
config will live, and its name and format?

**Comment by butlerx** [comment]
theres already a config.json but i fear that getting too big so `./config/mailingList.json`. would be best

**Comment by benwiley4000** [comment]
Thanks. I'll give it a shot!

**Comment by benwiley4000** [comment]
I've committed a functional prototype - you can try it out, but it's not ready for PR yet. Still todo is to use hexo's rendering engine to prepare the email body. Right now it just sends the markdown file.

https://github.com/benwiley4000/static-site/tree/email-mailing-list

Steps to test module from command line (isn't automatically run from `app.js` yet):

1. `node`
2. `> var emailNewPosts = require('emailNewPosts');`
3. `> emailNewPosts(function (err) { console.log(err); });`

If you have any errors, they'll be printed out.

NOTE: The address used for SMTP "from" will be the same address used for SMTP auth.

Pre-reqs:
* Create a file in the root directory called `mailing_list`. It's not json, it's a newline-separated list. Each line is an email address. If you don't include any email addresses you won't email anyone.
* Create a file in the root directory called `email_update_log`. It can be blank - if it is, running `emailNewPosts` will send an email for every post since the beginning of time to every user on your list. After that, the top line will display the latest timestamp and only newer posts will be sent to users' email inboxes.

Tips:
* If you want to send only one post to your mailing list, make the top line of `email_update_log` a date earlier than your latest post but later than all others. You can do this easily by hand with any date string recognized by JavaScript, e.g. "January 1, 2016."
* If you want to exclude some emails in the list from sending, just change the '@' sign to something else and that address will be ignored.

**Comment by butlerx** [comment]
This Is looking very good.
also realise i should have said this earlier, but its preferable for the email to be sent in plain text

**Comment by benwiley4000** [comment]
If you want only plain text and no html version, the work gets much easier. I haven't begun to really attempt the html rendering yet. Do you have a preferred email format?

**Comment by butlerx** [comment]
Plain text, character wrapping at 80 characters without the images is the basic formatting. The previous blog posts are all based off old emails. I'll grab a more recent one when I'm at the PC next :)   . We are trying to work towqrds the lowest common denominator which we know is a user using mutt

**Comment by benwiley4000** [comment]
Alright I'm on it. :)

**Comment by benwiley4000** [comment]
How should embedded links shown as text be handled?

**Comment by butlerx** [comment]
Ah yes they should just be the link address so what's in the () of the md

**Comment by benwiley4000** [comment]
I decided it makes the most sense to leave it as markdown, except for stripping images and html, and add important info/links at the top. I made the permalinks to match the scheme shown in the share button at the bottom of a post page, but those urls don't appear to actually exist yet, so I made the siteroot configurable in `config.json`. PR soon.

**Comment by benwiley4000** [comment]
Addressed by https://github.com/redbrick/static-site/pull/35.
