### ISSUE TITLE
concat css & js 

### ISSUE THREAD

**Issue by butlerx** [redbrick/static-site#72]
use hexo plugin to concat the css & js served

This may not be possible so a gulp process may have to be used [here](https://github.com/redbrick/hexo-theme-icarus) to do this instead

**Comment by butlerx** [comment]
haveing looked in to this it would likely have to be done in the theme

**Comment by iraquitan** [comment]
hi @butlerx I'd like to give it a try

**Comment by butlerx** [comment]
cool youll need to look at the theme repo [here](https://github.com/redbrick/hexo-theme-icarus) what we need is for all the js to get minified and concatenated together aswell all the css thats got from dep in the vendour directory need to be concated to one file.

**Comment by iraquitan** [comment]
Ok, thanks for the clarification. I prefer gulp as well.

**Comment by iraquitan** [comment]
hi @butlerx, just to be clear, the js to concat are the ones in the vendor folder or the ones in the source/js folder? Because if are the vendor ones, jquery is referenced in the [header](https://github.com/redbrick/hexo-theme-icarus/blob/master/layout/common/head.ejs#L46) while the other deps are in the [body](https://github.com/redbrick/hexo-theme-icarus/blob/master/layout/layout.ejs#L15).

also, if I concat the css in the [plugin/scripts.ejs](https://github.com/redbrick/hexo-theme-icarus/blob/master/layout/plugin/scripts.ejs#L3-L6) I will have to remove those lines os code there.

**Comment by butlerx** [comment]
so its both the ones in vendor and source/js. the concatenated js should be able to be in the body. but the order the files are concated together is important and needs to be the same as they are imported in the templates. also yes you'll need to remove all the css and html imports and just have imports for the concated files

**Comment by butlerx** [comment]
issue closed by @iraquitan
